import { Jost } from 'next/font/google';

const jost = Jost({
    subsets: ['latin'],
    weight: ['300', '500', '600', '700', '800'],
    style: ['normal', 'italic'],
});

// NOTE: storefront CSS (bootstrap, the MyMedi theme, antd reset, icon fonts) is
// imported in app/(app)/layout.jsx, NOT here. Keeping it out of the root layout
// is what lets app/(admin) and the Sanity studio render on a clean slate.

export const metadata = {
  title: "Healthfirst Medicorp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jost.className}>
      <body>{children}</body>
    </html>
  );
}
