-- =====================================================================
-- HealthFirst Medicorp — orders schema
-- Run this in the Neon SQL Editor (or `psql $DATABASE_URL -f this file`).
--
-- Safe to re-run: every statement is IF NOT EXISTS / idempotent.
--
-- Assumes these already exist (they do, verified against the live DB):
--   customers (customer_id BIGSERIAL PK, clerk_id TEXT UNIQUE, ...)
--   addresses (address_id BIGSERIAL PK, customer_id -> customers, ...)
-- =====================================================================


-- ---------------------------------------------------------------------
-- Human-readable invoice numbers: HFM-20260804-00001
--
-- Generated by the DB, not the app, so two concurrent checkouts can
-- never produce the same number. The counter is global (not reset per
-- day) — accountants want gap-free sequential invoice numbers, and a
-- per-day reset makes that impossible to prove.
-- ---------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS order_number_seq START 1;


-- ---------------------------------------------------------------------
-- ORDERS — one row per completed checkout
--
-- customer_id is the relationship you asked about: every order belongs
-- to exactly one customer, and customers.clerk_id ties that back to the
-- Clerk session. ON DELETE RESTRICT because deleting a customer who has
-- orders would destroy financial history.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  order_id          BIGSERIAL PRIMARY KEY,

  order_number      TEXT NOT NULL UNIQUE
                    DEFAULT (
                      'HFM-'
                      || to_char(now() AT TIME ZONE 'Asia/Kolkata', 'YYYYMMDD')
                      || '-'
                      || lpad(nextval('order_number_seq')::text, 5, '0')
                    ),

  customer_id       BIGINT NOT NULL
                    REFERENCES customers(customer_id) ON DELETE RESTRICT,

  -- Only set when the buyer ticked "save this address for future orders".
  -- The authoritative address for THIS order is shipping_address below.
  address_id        BIGINT
                    REFERENCES addresses(address_id) ON DELETE SET NULL,

  -- Frozen copy of the delivery address as entered at checkout. If the
  -- customer later edits or deletes that saved address, the invoice for
  -- this order must still show where it was actually shipped.
  shipping_address  JSONB NOT NULL,

  delivery_method   TEXT NOT NULL
                    CHECK (delivery_method IN ('standard', 'express', 'sameday')),
  payment_method    TEXT NOT NULL
                    CHECK (payment_method IN ('card', 'upi', 'cod')),

  -- Money. NUMERIC, never float — 0.1 + 0.2 must equal 0.3 on an invoice.
  subtotal          NUMERIC(12,2) NOT NULL CHECK (subtotal      >= 0),
  shipping_fee      NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
  tax               NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (tax           >= 0),
  total             NUMERIC(12,2) NOT NULL CHECK (total         >= 0),
  currency          TEXT NOT NULL DEFAULT 'INR',

  status            TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','confirmed','packed','shipped',
                                      'delivered','cancelled','refunded')),
  payment_status    TEXT NOT NULL DEFAULT 'unpaid'
                    CHECK (payment_status IN ('unpaid','paid','failed','refunded')),

  -- Invoice tracking, for the owner's dashboard.
  invoice_sent_at   TIMESTAMPTZ,
  notes             TEXT,

  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------
-- ORDER_ITEMS — one row per cart line
--
-- product_id is Sanity's string `id` field, deliberately NOT a foreign
-- key: Sanity is a separate system and a product can be deleted there.
-- product_name and unit_price are snapshots taken at purchase time, so
-- raising a price tomorrow does not silently rewrite yesterday's invoice.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
  order_item_id   BIGSERIAL PRIMARY KEY,
  order_id        BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,

  product_id      TEXT NOT NULL,
  product_name    TEXT NOT NULL,
  unit_price      NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
  quantity        INTEGER       NOT NULL CHECK (quantity > 0),
  line_total      NUMERIC(12,2) NOT NULL CHECK (line_total >= 0),

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- One line per product per order; quantity carries the count.
  UNIQUE (order_id, product_id)
);


-- ---------------------------------------------------------------------
-- PAYMENTS — one row per payment attempt
--
-- Separate from orders because an order can have zero, one, or several
-- attempts (retry after failure, refund later). Right now there is no
-- gateway, so each checkout writes a single 'pending' row with a NULL
-- provider_payment_id — the columns are already shaped for Razorpay or
-- Stripe when you wire one up.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
  payment_id           BIGSERIAL PRIMARY KEY,
  order_id             BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,

  provider             TEXT NOT NULL DEFAULT 'manual',  -- 'razorpay' | 'stripe' | 'cod' | 'manual'
  provider_payment_id  TEXT,                            -- NULL until a gateway responds
  method               TEXT,                            -- 'card' | 'upi' | 'cod'

  amount               NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  currency             TEXT NOT NULL DEFAULT 'INR',
  status               TEXT NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending','succeeded','failed',
                                         'refunded','partially_refunded')),
  failure_reason       TEXT,
  refunded_amount      NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (refunded_amount >= 0),

  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ---------------------------------------------------------------------
-- Indexes — sized for the owner's dashboard queries
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_orders_customer      ON orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at    ON orders (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status        ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_stat  ON orders (payment_status);

CREATE INDEX IF NOT EXISTS idx_order_items_order    ON order_items (order_id);
-- Drives the "units sold per product" KPI.
CREATE INDEX IF NOT EXISTS idx_order_items_product  ON order_items (product_id);

CREATE INDEX IF NOT EXISTS idx_payments_order       ON payments (order_id);


-- ---------------------------------------------------------------------
-- Keep updated_at honest without the app having to remember.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;
CREATE TRIGGER trg_orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_payments_updated_at ON payments;
CREATE TRIGGER trg_payments_updated_at
  BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_customers_updated_at ON customers;
CREATE TRIGGER trg_customers_updated_at
  BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- =====================================================================
-- Sanity check after running the above:
--
--   SELECT o.order_number, o.total, o.status,
--          c.first_name, c.last_name, c.email,
--          count(oi.order_item_id) AS lines
--   FROM orders o
--   JOIN customers   c  ON c.customer_id = o.customer_id
--   LEFT JOIN order_items oi ON oi.order_id = o.order_id
--   GROUP BY o.order_id, c.customer_id
--   ORDER BY o.created_at DESC;
-- =====================================================================
